apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: nodeapp
spec:
<<<<<<< HEAD
  replicas: 3
=======
  replicas: 4
>>>>>>> refs/remotes/origin/main
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: dockaleem/frontend:build-13010459619
        name: nodeapp
        resources: {}
